github.com:
    users:
        mdronytalukder42:
            oauth_token: ghu_894TXggawi9op433ogHqOHhs5C1nJ84CcXfK
    oauth_token: ghu_894TXggawi9op433ogHqOHhs5C1nJ84CcXfK
    user: mdronytalukder42
